Get btc price with websocket
21isenough/LightningATM pull request #55
Opened 2022-01-16 14:09 UTC by lth-elm

Instead of fetching the btc price only when calls are made we open at the launch of the application a websocket that will run in a thread and regularly update the btc and satoshis price per usd(t) in a global variable so that we gain some response time. Unfortunately coingecko and coinmarketcap doesn't offer websocket solution so I used the binance one but it only refer prices with stablecoins which are mostly usd stablecoins and no other currencies.

Fixes #19

2022-01-22 00:49 UTC, lightisfaster commented
Thank you for this nice feature. What do you think to have the "old" solution switchable in the config? I would test this PR the next day's.

2022-02-07 23:25 UTC, lightisfaster requested changes
Thanks for your PR.
The "old" solution should be switchable in the config because many users want to use their own local currency. The update interval should be adjustable in the config.ini, too.

2022-02-07 23:25 UTC, lightisfaster commented on config.py
> +BINANCE_SOCKET = "wss://stream.binance.com:9443/ws/btcusdt@kline_1m" # every 2 seconds
The "old" solution should be switchable in the config.
Many users want to use their own local currency

2022-02-07 23:25 UTC, lightisfaster commented on utils.py
> -    url = config.COINGECKO_URL_BASE + "simple/price"
The "old" solution should be switchable in the config.
Many users want to use their own local currency

2022-02-07 23:25 UTC, lightisfaster commented on utils.py
> +    time.sleep(2)
The update interval should be adjustable in the config.ini

2022-03-12 15:41 UTC, AxelHamburch commented
I think this is a really very interesting option!

I tested that. Unfortunately this didn't work with the old image "2019-04-08-raspbian-stretch-lightningatm.gz". Running the command `pip3 install -r requirements.txt` does not find the required "websocket-client==1.2.3". It was only when I used a recent image that he was able to install the actual websocket client.

I discovered an error in app.py line 231:

`config.BTCPRICE = config.btc_price`

But that leads to an error. It should be:

`config.BTCPRICE = utils.get_btc_price(config.conf["atm"]["cur"])`

Then it works!

2022-03-12 15:42 UTC, AxelHamburch commented
I think the image from 2019 with the "strech" os (V.9) is quite old and we should make a cut for the ATM and go to the latest version "bullseye" (V.11). When that's done we can also adjust the `requirements.txt` for this PR.

2022-03-17 08:36 UTC, AxelHamburch approved these changes

2022-03-17 08:55 UTC, AxelHamburch commented
The program is therefore executable and we only have the problem that it is not downward compatible due to the requirements of `websocket-client==1.2.3` in requirements.txt. The OS with Debian Version 9 (Stretch) only know the `websocket-client` up to version 0.59.0. Unfortunately, it then makes a module import error when it starts. I haven't found a way to change it later. Only with the new version 11 (Bullseye) does it run smoothly.
  
We should consider how we can get a clean cut where we can also add future new features

![2022-03-17 09_53_15-pi@raspberrypi_ ~_LightningATM](https://user-images.githubusercontent.com/84231978/158773113-0217846f-208a-4921-bc9f-80702d1d1241.png)
.

2023-03-18 20:49 UTC, closed without merging